### ISSUE TITLE
need help in running the hello world 

### ISSUE THREAD

**Issue by lakshmisivareddy** [aws/aws-greengrass-core-sdk-c#6]
Hi i am able to compile the sdk and generate the example binary's 

when i run the hello world program i am getting below error 
ERROR: Loaded stub instead of implementation library!

how can i run the binary's and check the connectivity with the aws cloud ?

**Comment by sjlevin** [comment]
The binary only runs properly on Greengrass. You need to upload it as an executible lambda and run it on a Greengrass device. https://docs.aws.amazon.com/greengrass/latest/developerguide/lambda-functions.html#lambda-executables

**Comment by ShirleyZheng92** [comment]
If you try to run the compiled binary it will return this error, since you are compiling against just the sdk interface (not implementation) . You need to upload the binary as lambda & deploy to a Greengrass group

**Comment by fengwang666** [comment]
Close the issue.
