### ISSUE TITLE
Support for Streams

### ISSUE THREAD

**Issue by mariotoffia** [aws/aws-greengrass-core-sdk-c#7]
Hi and thanks for a very nice SDK!

We have starting using this SDK to realize our plant to integrate our cloud solution with both sensors and SCADA systems that sits on different backend system.

We are considering using the [StreamsClient](https://docs.aws.amazon.com/greengrass/latest/developerguide/work-with-streams.html) option but it does not exist in your C SDK. 

Would it be possible to add this support?

Cheers,
 Mario

**Comment by cadubentzen** [comment]
I would love to use this feature too, in my case via the Rust SDK

**Comment by mariotoffia** [comment]
@jpeddicord  and @amzn-xyxu Do you take feature requests? If not, please tell us then I'll just close this issue.

Thanks
 Mario :)

**Comment by mariotoffia** [comment]
Seems abandoned - closing issue
